import { Poppins } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Footer from './components/sharedComponet/footer'
import NavbarCustom from './components/sharedComponet/navbar';

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'], 
  weight: ['400', '600', '700'], 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavbarCustom />
        <main className='container mt-[40px] py-24 flex min-h-screen flex-col  justify-between' >

        {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
